language: ruby
rvm:
- 2.2.2
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec
- bundle exec cucumber
after_script:
- bundle exec rake send_to_codeclimate
notifications:
  slack:
    secure: QkSzTqvCJSO5Gk7hcd2KcFo1+6UU29h81RqNGY79oi8dE6kO7KB5WGR9Avsmr85wuIDtx39HNDOES9duqKmK1at5bBD0fqIxmhIuUHlbiYE/mnuS4BFfbGFOer9osVFJtJCWeIFocCoRNE3/JDIw4SoK8+VVZKDhkdticCuMqTAX+p6qUb6qe22LzgxvV33hGqicRGLvW0Y0ct8bIFW/YBiykNdtGfDMDNS++X/Lh3Mnu8ZOk+6PtQucPqDrF4BU0sEbJzyg5PV0ftWVmXltMoUWHtYbPrsNaelfP+dcbQcWG7s5jxD8shHPOrWEIr3sUxcHmuhWoARm4Eg7hdMxjChh2LDjATMvT6bJ6fr4+Z0nvfaogqyxXJYg3UeAVEOwGUDfUs4TrqmD9zF9g8+pyf/hKO5yOlmV1zpE30PAt4+heIUvAJb9nYgnGS5/QquS9nBDGeYGi9aosq9jeE8Di1ivE7i5t6cXrcqBZf26ykwc2fv/0wR/wPCAJKhT4SiuqLT0pBuLJlrhIOEWBORUcn7OQvQFhYqjDtyQAznXmRqxF8XcIjvlJ6Nz09/Rg1n7R8NhdPQWhskW7cB0EnaQ7Z9u1XlV6hZqTWQJLe02aeY4Sjl3cqBssdXOPwSL9JslWan6lezqXKUAU7UBpYTsL3G0Beh1Kx+n67JhuvTHubE=
